"""empty message

Revision ID: 684aa1c4b322
Revises: fb33b3c82df6
Create Date: 2025-05-26 21:07:42.896842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '684aa1c4b322'
down_revision: Union[str, None] = 'fb33b3c82df6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model_variants', 'price',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model_variants', 'price',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
