"""empty message

Revision ID: 733a0a8540a1
Revises: 0d2cf107006d
Create Date: 2025-05-08 15:34:18.719562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '733a0a8540a1'
down_revision: Union[str, None] = '0d2cf107006d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.add_column('orders', sa.Column('status_id', sa.Integer(), nullable=True))
    op.alter_column('orders', 'total_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Integer(),
               nullable=False)
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'order_statuses', ['status_id'], ['id'])
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.alter_column('orders', 'total_price',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.drop_column('orders', 'status_id')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    # ### end Alembic commands ###
